openapi: 3.0.3
info:
    title: Argent Bank Transaction API
    description: API for managing user transactions, including retrieving, creating, updating, and deleting transactions.
    version: 1.0.0

tags:
    - name: Transactions
      description: Endpoints related to managing transactions.

paths:
    /transactions:
        get:
            tags:
                - Transactions
            summary: Retrieve all transactions for a specific account.
            parameters:
                - name: accountId
                  in: query
                  description: The ID of the account to fetch transactions for.
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: A list of transactions.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Transaction'
                '404':
                    description: Account not found.
                '500':
                    description: Server error.

        post:
            tags:
                - Transactions
            summary: Create a new transaction.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Transaction'
            responses:
                '201':
                    description: Transaction created successfully.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transaction'
                '400':
                    description: Invalid input data.
                '500':
                    description: Server error.

    /transactions/{transactionId}:
        get:
            tags:
                - Transactions
            summary: Retrieve details of a specific transaction.
            parameters:
                - name: transactionId
                  in: path
                  description: The unique ID of the transaction.
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Transaction details.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transaction'
                '404':
                    description: Transaction not found.
                '500':
                    description: Server error.

        put:
            tags:
                - Transactions
            summary: Update an existing transaction.
            parameters:
                - name: transactionId
                  in: path
                  description: The unique ID of the transaction to update.
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Transaction'
            responses:
                '200':
                    description: Transaction updated successfully.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transaction'
                '400':
                    description: Invalid input data.
                '404':
                    description: Transaction not found.
                '500':
                    description: Server error.

        delete:
            tags:
                - Transactions
            summary: Delete a specific transaction.
            parameters:
                - name: transactionId
                  in: path
                  description: The unique ID of the transaction to delete.
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Transaction deleted successfully.
                '404':
                    description: Transaction not found.
                '500':
                    description: Server error.

components:
    schemas:
        Transaction:
            type: object
            properties:
                id:
                    type: string
                    description: Unique identifier of the transaction.
                date:
                    type: string
                    format: date
                    description: Date of the transaction.
                description:
                    type: string
                    description: Description of the transaction.
                amount:
                    type: number
                    format: float
                    description: Amount of the transaction.
                accountId:
                    type: string
                    description: ID of the account associated with the transaction.
